export const HIDE_UNDERLAYER = 'HIDE_UNDERLAYER';
export const SHOW_UNDERLAYER = 'SHOW_UNDERLAYER';

export const BOOK_DATA_FAILURE = 'BOOK_DATA_FAILURE';
export const BOOK_DATA_REQUEST = 'BOOK_DATA_REQUEST';
export const BOOK_DATA_SUCCESS = 'BOOK_DATA_SUCCESS';

export const BOOKS_I_READ_FAILURE = 'BOOKS_I_READ_FAILURE';
export const BOOKS_I_READ_REQUEST = 'BOOKS_I_READ_REQUEST';
export const BOOKS_I_READ_SUCCESS = 'BOOKS_I_READ_SUCCESS';

export const MY_BOOKS_FAILURE = 'MY_BOOKS_FAILURE';
export const MY_BOOKS_REQUEST = 'MY_BOOKS_REQUEST';
export const MY_BOOKS_SUCCESS = 'MY_BOOKS_SUCCESS';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIGN_OUT = 'SIGN_OUT';

export const ADD_MY_BOOK_REQUEST = 'ADD_MY_BOOK_REQUEST';
export const ADD_MY_BOOK_FAILURE = 'ADD_MY_BOOK_FAILURE';
export const ADD_MY_BOOK_SUCCESS = 'ADD_MY_BOOK_SUCCESS';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const REMOVE_QUEUE_FAILURE = 'REMOVE_QUEUE_FAILURE';
export const REMOVE_QUEUE_REQUEST = 'REMOVE_QUEUE_REQUEST';
export const REMOVE_QUEUE_SUCCESS = 'REMOVE_QUEUE_SUCCESS';

export const RATE_BOOK_REQUEST = 'RATE_BOOK_REQUEST';
export const RATE_BOOK_SUCCESS = 'RATE_BOOK_SUCCESS';
export const RATE_BOOK_FAILURE = 'RATE_BOOK_FAILURE';
