export const HIDE_UNDERLAYER = 'HIDE_UNDERLAYER';
export const SHOW_UNDERLAYER = 'SHOW_UNDERLAYER';

export const BOOK_DATA_FAILURE = 'BOOK_DATA_FAILURE';
export const BOOK_DATA_REQUEST = 'BOOK_DATA_REQUEST';
export const BOOK_DATA_SUCCESS = 'BOOK_DATA_SUCCESS';

export const MY_BOOKS_FAILURE = 'MY_BOOKS_FAILURE';
export const MY_BOOKS_REQUEST = 'MY_BOOKS_REQUEST';
export const MY_BOOKS_SUCCESS = 'MY_BOOKS_SUCCESS';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const ACCOUNT_REQUEST = 'ACCOUNT_REQUEST';
export const ACCOUNT_FAILURE = 'ACCOUNT_FAILURE';
export const ACCOUNT_SUCCESS = 'ACCOUNT_SUCCESS';

export const SIGN_OUT = 'SIGN_OUT';

export const ADD_MY_BOOK_REQUEST = 'ADD_MY_BOOK_REQUEST';
export const ADD_MY_BOOK_FAILURE = 'ADD_MY_BOOK_FAILURE';
export const ADD_MY_BOOK_SUCCESS = 'ADD_MY_BOOK_SUCCESS';