# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ESBooks' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'GoogleSignIn', '~> 4.3.0'
  # Pods for ESBooks
end

target 'ESBooks-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ESBooks-tvOS

end
