# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'lottie-ios', :path => '../node_modules/lottie-ios'
pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

target 'ESBooks' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ESBooks

  target 'ESBooks-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  end

  target 'ESBooksTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ESBooks-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ESBooks-tvOS

  target 'ESBooks-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
